//! Native desktop shell: tray icon plus an on-demand dashboard window around
//! the shared owner runtime. The window is created when shown and dropped
//! when closed; the tray keeps running. No SQL and no filesystem access
//! happen here — every intent becomes a core `Request`.
mod actions;
mod dialogs;
mod donut;
mod forms;
mod view;

#[allow(missing_debug_implementations)] // generated by slint-build
pub mod ui {
    slint::include_modules!();
}

use mogumogu::config::Config;
use mogumogu::domain::{PlanSummary, Settings, Snapshot};
use mogumogu::owner::{Owner, OwnerEvents};
use mogumogu::service::Request;
use serde_json::Value;
use slint::ComponentHandle;
use std::cell::RefCell;
use std::time::Duration;
use ui::*;

thread_local! {
    static DESKTOP: RefCell<Option<Desktop>> = const { RefCell::new(None) };
}

fn with(f: impl FnOnce(&mut Desktop)) {
    DESKTOP.with(|cell| {
        if let Some(desktop) = cell.borrow_mut().as_mut() {
            f(desktop);
        }
    });
}

/// Defers to the next event-loop turn so Slint callbacks never re-enter.
fn later(f: impl FnOnce(&mut Desktop) + 'static) {
    slint::Timer::single_shot(Duration::ZERO, move || with(f));
}

#[derive(Clone, Copy, Debug)]
enum Form {
    None,
    Project,
    Scratch,
}

struct Desktop {
    owner: Owner,
    tray: MoguTray,
    dashboard: Option<Dashboard>,
    snapshot: Snapshot,
    busy: bool,
    status: String,
    data_path: String,
    form: Form,
}

/// Worker-thread events forwarded into the UI thread.
struct UiEvents;

type Outcome = Result<Value, String>;

impl OwnerEvents for UiEvents {
    fn snapshot(&self, snapshot: Snapshot) {
        let _ = slint::invoke_from_event_loop(move || with(|d| d.accept(snapshot)));
    }
    fn outcome(&self, request: &Request, result: &mogumogu::Result<Value>) {
        let request = request.clone();
        let result: Outcome = match result {
            Ok(value) => Ok(value.clone()),
            Err(error) => Err(error.to_string()),
        };
        let _ = slint::invoke_from_event_loop(move || with(|d| d.outcome(request, result)));
    }
    fn busy(&self, busy: bool) {
        let _ = slint::invoke_from_event_loop(move || with(|d| d.set_busy(busy)));
    }
    fn show_dashboard(&self) {
        let _ = slint::invoke_from_event_loop(|| with(Desktop::show_or_report));
    }
    fn hide_dashboard(&self) {
        let _ = slint::invoke_from_event_loop(|| with(Desktop::hide));
    }
    fn shutdown(&self) {
        let _ = slint::invoke_from_event_loop(|| {
            let _ = slint::quit_event_loop();
        });
    }
}

pub fn run(config: Config, show: bool) -> Result<(), Box<dyn std::error::Error>> {
    let tray = MoguTray::new()?;
    let data_path = config.database_path().to_string_lossy().into_owned();
    let demo = config.demo;
    let owner = Owner::start(config, UiEvents)?;
    tray.on_show_dashboard(|| with(Desktop::show_or_report));
    tray.on_refresh_inventory(|| with(|d| d.owner.refresh()));
    tray.on_scan_all(|| with(|d| d.submit(Request::Scan { scope_id: None })));
    tray.on_toggle_monitoring(|| with(|d| d.change_settings(|s| s.monitoring_enabled = !s.monitoring_enabled)));
    tray.on_exit_app(|| {
        let _ = slint::quit_event_loop();
    });
    DESKTOP.with(|cell| {
        *cell.borrow_mut() = Some(Desktop {
            owner,
            tray,
            dashboard: None,
            snapshot: Snapshot { demo, ..Default::default() },
            busy: false,
            status: "Inventar wird geladen …".into(),
            data_path,
            form: Form::None,
        });
    });
    if show {
        with(Desktop::show_or_report);
    }
    let result = slint::run_event_loop_until_quit();
    // Stops IPC and worker, then releases tray and window.
    DESKTOP.with(|cell| drop(cell.borrow_mut().take()));
    result?;
    Ok(())
}

impl Desktop {
    fn show_or_report(&mut self) {
        if let Err(error) = self.show() {
            mogumogu::platform::show_error("mogumogu", &error.to_string());
        }
    }

    fn show(&mut self) -> Result<(), slint::PlatformError> {
        if self.dashboard.is_none() {
            let ui = Dashboard::new()?;
            actions::wire(&ui);
            self.dashboard = Some(ui);
            self.render_snapshot();
        }
        if let Some(ui) = &self.dashboard {
            ui.show()?;
        }
        Ok(())
    }

    /// Dropping the component releases its models and views; the tray and
    /// the owner keep running.
    fn hide(&mut self) {
        if let Some(ui) = self.dashboard.take() {
            let _ = ui.hide();
        }
    }

    fn render_snapshot(&self) {
        if let Some(ui) = &self.dashboard {
            view::render_snapshot(ui, &self.snapshot, &self.data_path);
            view::render_status(ui, self.busy, &self.status);
        }
    }

    fn render_status(&self) {
        if let Some(ui) = &self.dashboard {
            view::render_status(ui, self.busy, &self.status);
        }
    }

    fn accept(&mut self, snapshot: Snapshot) {
        self.snapshot = snapshot;
        let settings = self.snapshot.settings.clone().unwrap_or_default();
        let hints = self.snapshot.review_count();
        let hint = if settings.notifications_enabled && hints > 0 {
            format!("mogumogu · {hints} Prüfhinweise")
        } else {
            "mogumogu · lokales Entwicklungsinventar".into()
        };
        self.tray.set_hint(hint.into());
        self.tray.set_local(!self.snapshot.demo);
        self.tray.set_monitoring(settings.monitoring_enabled);
        if !self.busy {
            self.status = self.default_status();
        }
        self.render_snapshot();
    }

    fn default_status(&self) -> String {
        let s = &self.snapshot;
        let settings = s.settings.clone().unwrap_or_default();
        if s.demo {
            return "Demodaten · eigene Datenbank · kein Dateisystemscan · keine Netzwerkabfragen".into();
        }
        format!(
            "Lokales Inventar · SQLite {} · {} Lesefreigaben · Überwachung {} · Updatehinweise {} · Bereinigung nur in Wegwerf-Testwurzeln",
            s.sqlite_version,
            s.scopes.len(),
            if settings.monitoring_enabled { "an" } else { "aus" },
            if settings.network_updates_enabled { "an" } else { "aus" }
        )
    }

    fn set_busy(&mut self, busy: bool) {
        const WORKING: &str = "Wird bearbeitet …";
        self.busy = busy;
        self.tray.set_busy(busy);
        if busy {
            self.status = WORKING.into();
        } else if self.status == WORKING {
            self.status = self.default_status();
        }
        self.render_status();
    }

    fn submit(&mut self, request: Request) {
        if self.snapshot.demo && request.is_write() {
            self.dialog(dialogs::message(
                "Demodaten bleiben unverändert",
                "Die Vorschau enthält ausschließlich Beispieldaten und ist schreibgeschützt.\n\nFür dein eigenes Inventar \
                 mogumogu über das Tray-Menü beenden und mit .\\start.ps1 -Mode Local starten.",
            ));
            return;
        }
        if !self.owner.submit(request) {
            self.status = "Der Kern ist ausgelastet; bitte gleich erneut versuchen.".into();
            self.render_status();
        } else {
            // Feedback immediately, before the worker's event reaches the UI.
            self.set_busy(true);
        }
    }

    fn change_settings(&mut self, change: impl FnOnce(&mut Settings)) {
        let mut settings = self.snapshot.settings.clone().unwrap_or_default();
        change(&mut settings);
        self.submit(Request::SaveSettings { settings });
    }

    fn outcome(&mut self, request: Request, result: Outcome) {
        let value = match result {
            Ok(value) => value,
            Err(message) => {
                self.status = message.clone();
                if let Some(ui) = &self.dashboard
                    && ui.global::<Store>().get_modal() == 2
                    && !matches!(self.form, Form::None)
                {
                    ui.global::<Store>().set_form_error(message.into());
                    self.render_status();
                    return;
                }
                self.dialog(dialogs::message("Vorgang nicht abgeschlossen", &message));
                return;
            }
        };
        match request {
            Request::RegisterProject { .. } => {
                self.close_modal();
                self.status = "Projekt registriert – Lesefreigabe ist ein eigener Schritt.".into();
                if let Some(id) = value["project_id"].as_i64() {
                    later(move |d| d.open_project(id));
                }
            }
            Request::ApproveProject { .. } => {
                self.close_modal();
                if let Some(scope_id) = value["scope_id"].as_i64() {
                    self.status = "Lesefreigabe erteilt – erste Erfassung startet.".into();
                    self.submit(Request::Scan { scope_id: Some(scope_id) });
                }
            }
            Request::Scan { .. } => {
                let reports = value.as_array().map(Vec::as_slice).unwrap_or_default();
                let summary: Vec<String> = reports
                    .iter()
                    .map(|r| match r["problem"].as_str() {
                        Some(problem) => format!("Bereich {}: {problem}", r["scope_id"]),
                        None if r["baseline"] == true => format!("Bereich {}: Vergleichsbasis erstellt", r["scope_id"]),
                        None => format!(
                            "Bereich {}: {} neu, {} entfernt, {} geändert ({})",
                            r["scope_id"],
                            r["added"],
                            r["removed"],
                            r["changed"],
                            r["state"].as_str().unwrap_or("?")
                        ),
                    })
                    .collect();
                self.status =
                    if summary.is_empty() { "Keine freigegebenen Bereiche.".into() } else { summary.join(" · ") };
            }
            Request::MeasureResource { .. } | Request::MeasureScope { .. } => {
                let text = match value["bytes"].as_i64() {
                    Some(bytes) => format!("Gemessen: {}", mogumogu::domain::format_bytes(Some(bytes))),
                    None => {
                        format!("Größe unbekannt: {}", value["reason"].as_str().unwrap_or("unvollständige Messung"))
                    }
                };
                self.status = text.clone();
                self.dialog(dialogs::message("Größenmessung", &text));
            }
            Request::CleanupPlan { .. }
            | Request::CleanupApprove { .. }
            | Request::CleanupApply { .. }
            | Request::CleanupCancel { .. }
            | Request::CleanupReconcile { .. } => {
                if let Ok(plan) = serde_json::from_value::<PlanSummary>(value) {
                    self.status = format!("Plan {}: {}", plan.id, plan.state.label());
                    self.dialog(dialogs::plan(&plan));
                }
            }
            Request::Updates => {
                self.status = format!(
                    "Updatehinweise: {} geprüft, {} neuer, {} privat übersprungen, {} Quelle nicht freigegeben, {} fehlgeschlagen",
                    value["checked"],
                    value["available"],
                    value["skipped_private"],
                    value["not_approved"],
                    value["failed"]
                );
            }
            Request::ScratchCreate { .. } => {
                self.close_modal();
                self.status = "Scratchpad angelegt (source, environment, temporary, results).".into();
            }
            Request::SaveSettings { .. } => self.status = "Einstellungen gespeichert.".into(),
            _ => {
                self.close_modal();
                self.status = "Gespeichert.".into();
            }
        }
        self.render_status();
    }
}

fn defer_hide() {
    later(Desktop::hide);
}
