//! Native desktop shell: tray icon plus an on-demand dashboard window around
//! the shared owner runtime. The window is created when shown and dropped
//! when closed; the tray keeps running. No SQL and no filesystem access
//! happen here — every intent becomes a core `Request`.
mod dialogs;
mod donut;
mod view;

#[allow(missing_debug_implementations)] // generated by slint-build
pub mod ui {
    slint::include_modules!();
}

use dialogs::Dialog;
use mogumogu::config::Config;
use mogumogu::domain::{PlanSummary, Settings, Snapshot};
use mogumogu::owner::{Owner, OwnerEvents};
use mogumogu::service::Request;
use serde_json::Value;
use slint::{ComponentHandle, ModelRc, SharedString, VecModel};
use std::cell::RefCell;
use std::rc::Rc;
use std::time::Duration;
use ui::*;

thread_local! {
    static DESKTOP: RefCell<Option<Desktop>> = const { RefCell::new(None) };
}

fn with(f: impl FnOnce(&mut Desktop)) {
    DESKTOP.with(|cell| {
        if let Some(desktop) = cell.borrow_mut().as_mut() {
            f(desktop);
        }
    });
}

/// Defers to the next event-loop turn so Slint callbacks never re-enter.
fn later(f: impl FnOnce(&mut Desktop) + 'static) {
    slint::Timer::single_shot(Duration::ZERO, move || with(f));
}

#[derive(Clone, Copy, Debug)]
enum Form {
    None,
    Project,
    Scratch,
}

struct Desktop {
    owner: Owner,
    tray: MoguTray,
    dashboard: Option<Dashboard>,
    snapshot: Snapshot,
    busy: bool,
    status: String,
    data_path: String,
    form: Form,
}

/// Worker-thread events forwarded into the UI thread.
struct UiEvents;

type Outcome = Result<Value, String>;

impl OwnerEvents for UiEvents {
    fn snapshot(&self, snapshot: Snapshot) {
        let _ = slint::invoke_from_event_loop(move || with(|d| d.accept(snapshot)));
    }
    fn outcome(&self, request: &Request, result: &mogumogu::Result<Value>) {
        let request = request.clone();
        let result: Outcome = match result {
            Ok(value) => Ok(value.clone()),
            Err(error) => Err(error.to_string()),
        };
        let _ = slint::invoke_from_event_loop(move || with(|d| d.outcome(request, result)));
    }
    fn busy(&self, busy: bool) {
        let _ = slint::invoke_from_event_loop(move || with(|d| d.set_busy(busy)));
    }
    fn show_dashboard(&self) {
        let _ = slint::invoke_from_event_loop(|| with(Desktop::show_or_report));
    }
    fn hide_dashboard(&self) {
        let _ = slint::invoke_from_event_loop(|| with(Desktop::hide));
    }
    fn shutdown(&self) {
        let _ = slint::invoke_from_event_loop(|| {
            let _ = slint::quit_event_loop();
        });
    }
}

pub fn run(config: Config, show: bool) -> Result<(), Box<dyn std::error::Error>> {
    let tray = MoguTray::new()?;
    let data_path = config.database_path().to_string_lossy().into_owned();
    let demo = config.demo;
    let owner = Owner::start(config, UiEvents)?;
    tray.on_show_dashboard(|| with(Desktop::show_or_report));
    tray.on_refresh_inventory(|| with(|d| d.owner.refresh()));
    tray.on_scan_all(|| with(|d| d.submit(Request::Scan { scope_id: None })));
    tray.on_toggle_monitoring(|| with(|d| d.change_settings(|s| s.monitoring_enabled = !s.monitoring_enabled)));
    tray.on_exit_app(|| {
        let _ = slint::quit_event_loop();
    });
    DESKTOP.with(|cell| {
        *cell.borrow_mut() = Some(Desktop {
            owner,
            tray,
            dashboard: None,
            snapshot: Snapshot { demo, ..Default::default() },
            busy: false,
            status: "Inventar wird geladen …".into(),
            data_path,
            form: Form::None,
        });
    });
    if show {
        with(Desktop::show_or_report);
    }
    let result = slint::run_event_loop_until_quit();
    // Stops IPC and worker, then releases tray and window.
    DESKTOP.with(|cell| drop(cell.borrow_mut().take()));
    result?;
    Ok(())
}

fn model<T: Clone + 'static>(items: Vec<T>) -> ModelRc<T> {
    Rc::new(VecModel::from(items)).into()
}

impl Desktop {
    fn show_or_report(&mut self) {
        if let Err(error) = self.show() {
            mogumogu::platform::show_error("mogumogu", &error.to_string());
        }
    }

    fn show(&mut self) -> Result<(), slint::PlatformError> {
        if self.dashboard.is_none() {
            let ui = Dashboard::new()?;
            wire(&ui);
            self.dashboard = Some(ui);
            self.render();
        }
        if let Some(ui) = &self.dashboard {
            ui.show()?;
        }
        Ok(())
    }

    /// Dropping the component releases its models and views; the tray and
    /// the owner keep running.
    fn hide(&mut self) {
        if let Some(ui) = self.dashboard.take() {
            let _ = ui.hide();
        }
    }

    fn render(&self) {
        if let Some(ui) = &self.dashboard {
            view::render(
                ui,
                &view::ViewState {
                    snapshot: &self.snapshot,
                    busy: self.busy,
                    status: &self.status,
                    data_path: &self.data_path,
                },
            );
        }
    }

    fn accept(&mut self, snapshot: Snapshot) {
        self.snapshot = snapshot;
        let settings = self.snapshot.settings.clone().unwrap_or_default();
        let hints = self.snapshot.review_count();
        let hint = if settings.notifications_enabled && hints > 0 {
            format!("mogumogu · {hints} Prüfhinweise")
        } else {
            "mogumogu · lokales Entwicklungsinventar".into()
        };
        self.tray.set_hint(hint.into());
        self.tray.set_local(!self.snapshot.demo);
        self.tray.set_monitoring(settings.monitoring_enabled);
        if !self.busy {
            self.status = self.default_status();
        }
        self.render();
    }

    fn default_status(&self) -> String {
        let s = &self.snapshot;
        let settings = s.settings.clone().unwrap_or_default();
        if s.demo {
            return "Demodaten · eigene Datenbank · kein Dateisystemscan · keine Netzwerkabfragen".into();
        }
        format!(
            "Lokales Inventar · SQLite {} · {} Lesefreigaben · Überwachung {} · Updatehinweise {} · Bereinigung nur in Wegwerf-Testwurzeln",
            s.sqlite_version,
            s.scopes.len(),
            if settings.monitoring_enabled { "an" } else { "aus" },
            if settings.network_updates_enabled { "an" } else { "aus" }
        )
    }

    fn set_busy(&mut self, busy: bool) {
        const WORKING: &str = "Wird bearbeitet …";
        self.busy = busy;
        if busy {
            self.status = WORKING.into();
        } else if self.status == WORKING {
            self.status = self.default_status();
        }
        self.render();
    }

    fn submit(&mut self, request: Request) {
        if self.snapshot.demo && request.is_write() {
            self.dialog(dialogs::message(
                "Demodaten bleiben unverändert",
                "Die Vorschau enthält ausschließlich Beispieldaten und ist schreibgeschützt.\n\nFür dein eigenes Inventar \
                 mogumogu über das Tray-Menü beenden und mit .\\start.ps1 -Mode Local starten.",
            ));
            return;
        }
        if !self.owner.submit(request) {
            self.status = "Der Kern ist ausgelastet; bitte gleich erneut versuchen.".into();
            self.render();
        }
    }

    fn change_settings(&mut self, change: impl FnOnce(&mut Settings)) {
        let mut settings = self.snapshot.settings.clone().unwrap_or_default();
        change(&mut settings);
        self.submit(Request::SaveSettings { settings });
    }

    fn outcome(&mut self, request: Request, result: Outcome) {
        let value = match result {
            Ok(value) => value,
            Err(message) => {
                self.status = message.clone();
                self.dialog(dialogs::message("Vorgang nicht abgeschlossen", &message));
                return;
            }
        };
        match request {
            Request::RegisterProject { .. } => {
                self.close_modal();
                self.status = "Projekt registriert – Lesefreigabe ist ein eigener Schritt.".into();
                if let Some(id) = value["project_id"].as_i64() {
                    later(move |d| d.open_project(id));
                }
            }
            Request::ApproveProject { .. } => {
                self.close_modal();
                if let Some(scope_id) = value["scope_id"].as_i64() {
                    self.status = "Lesefreigabe erteilt – erste Erfassung startet.".into();
                    self.submit(Request::Scan { scope_id: Some(scope_id) });
                }
            }
            Request::Scan { .. } => {
                let reports = value.as_array().cloned().unwrap_or_default();
                let summary: Vec<String> = reports
                    .iter()
                    .map(|r| match r["problem"].as_str() {
                        Some(problem) => format!("Bereich {}: {problem}", r["scope_id"]),
                        None if r["baseline"] == true => format!("Bereich {}: Vergleichsbasis erstellt", r["scope_id"]),
                        None => format!(
                            "Bereich {}: {} neu, {} entfernt, {} geändert ({})",
                            r["scope_id"],
                            r["added"],
                            r["removed"],
                            r["changed"],
                            r["state"].as_str().unwrap_or("?")
                        ),
                    })
                    .collect();
                self.status =
                    if summary.is_empty() { "Keine freigegebenen Bereiche.".into() } else { summary.join(" · ") };
            }
            Request::MeasureResource { .. } | Request::MeasureScope { .. } => {
                let text = match value["bytes"].as_i64() {
                    Some(bytes) => format!("Gemessen: {}", mogumogu::domain::format_bytes(Some(bytes))),
                    None => {
                        format!("Größe unbekannt: {}", value["reason"].as_str().unwrap_or("unvollständige Messung"))
                    }
                };
                self.status = text.clone();
                self.dialog(dialogs::message("Größenmessung", &text));
            }
            Request::CleanupPlan { .. }
            | Request::CleanupApprove { .. }
            | Request::CleanupApply { .. }
            | Request::CleanupCancel { .. }
            | Request::CleanupReconcile { .. } => {
                if let Ok(plan) = serde_json::from_value::<PlanSummary>(value) {
                    self.status = format!("Plan {}: {}", plan.id, plan.state.label());
                    self.dialog(dialogs::plan(&plan));
                }
            }
            Request::Updates => {
                self.status = format!(
                    "Updatehinweise: {} geprüft, {} neuer, {} privat übersprungen, {} Quelle nicht freigegeben, {} fehlgeschlagen",
                    value["checked"],
                    value["available"],
                    value["skipped_private"],
                    value["not_approved"],
                    value["failed"]
                );
            }
            Request::ScratchCreate { .. } => {
                self.close_modal();
                self.status = "Scratchpad angelegt (source, environment, temporary, results).".into();
            }
            Request::SaveSettings { .. } => self.status = "Einstellungen gespeichert.".into(),
            _ => {
                self.close_modal();
                self.status = "Gespeichert.".into();
            }
        }
        self.render();
    }

    // ------------------------------------------------------------ dialogs

    fn dialog(&mut self, dialog: Dialog) {
        let Some(ui) = &self.dashboard else { return };
        let store = ui.global::<Store>();
        store.set_detail_title(dialog.title.into());
        store.set_detail_path(dialog.path.into());
        store.set_detail_body(dialog.body.into());
        store.set_detail_rows(model(
            dialog
                .rows
                .into_iter()
                .map(|(label, value)| DetailRow { label: label.into(), value: value.into() })
                .collect(),
        ));
        store.set_detail_actions(model(
            dialog
                .actions
                .into_iter()
                .map(|(id, label, primary)| DetailAction { id: id.into(), label: label.into(), primary })
                .collect(),
        ));
        self.form = Form::None;
        store.set_modal(1);
        ui.invoke_focus_dialog();
    }

    fn form(&mut self, form: Form, title: &str, text: &str, fields: [(&str, &str, String); 2], submit: &str) {
        let Some(ui) = &self.dashboard else { return };
        let store = ui.global::<Store>();
        store.set_form_title(title.into());
        store.set_form_text(text.into());
        let [(label1, hint1, value1), (label2, hint2, value2)] = fields;
        store.set_form_label_1(label1.into());
        store.set_form_hint_1(hint1.into());
        store.set_form_value_1(value1.into());
        store.set_form_label_2(label2.into());
        store.set_form_hint_2(hint2.into());
        store.set_form_value_2(value2.into());
        store.set_form_submit(submit.into());
        self.form = form;
        store.set_modal(2);
        ui.invoke_focus_dialog();
    }

    fn close_modal(&mut self) {
        if let Some(ui) = &self.dashboard {
            ui.global::<Store>().set_modal(0);
        }
        self.form = Form::None;
    }

    fn open_project(&mut self, id: i64) {
        if let Some(project) = self.snapshot.projects.iter().find(|p| p.id == id).cloned() {
            let dialog = dialogs::project(&self.snapshot, &project);
            self.dialog(dialog);
        }
    }

    fn open_resource(&mut self, id: i64) {
        if let Some(resource) = self.snapshot.resources.iter().find(|r| r.id == id).cloned() {
            let dialog = dialogs::resource(&self.snapshot, &resource);
            self.dialog(dialog);
        }
    }

    fn new_project(&mut self) {
        if self.snapshot.demo {
            self.submit(Request::RegisterProject { name: String::new(), path: String::new() });
            return;
        }
        self.form(
            Form::Project,
            "Projekt registrieren",
            "Nur Name und Pfad werden gespeichert. Der Ordner wird nicht gelesen, erstellt oder verändert; die Lesefreigabe ist ein eigener Schritt.",
            [
                ("Projektname", "Zum Beispiel: api-service", String::new()),
                ("Lokaler Windows-Pfad", "C:\\dev\\api-service", String::new()),
            ],
            "Geschützt registrieren",
        );
    }

    fn new_scratch(&mut self, project_id: Option<i64>) {
        if self.snapshot.demo {
            self.submit(Request::ScratchCreate {
                project_id: 0,
                name: String::new(),
                purpose: String::new(),
                review_days: None,
            });
            return;
        }
        let project = project_id.or_else(|| self.snapshot.projects.first().map(|p| p.id));
        self.form(
            Form::Scratch,
            "Scratchpad anlegen",
            "mogumogu legt unter der Scratchpad-Wurzel source, environment, temporary und results an. Quelle und Ergebnisse bleiben immer erhalten.",
            [
                ("Name", "Zum Beispiel: parser-spike", String::new()),
                ("Projekt-Nr.", "1", project.map(|p| p.to_string()).unwrap_or_default()),
            ],
            "Anlegen",
        );
    }

    fn submit_form(&mut self, first: String, second: String) {
        match self.form {
            Form::Project => self.submit(Request::RegisterProject { name: first, path: second }),
            Form::Scratch => match second.trim().parse::<i64>() {
                Ok(project_id) => self.submit(Request::ScratchCreate {
                    project_id,
                    name: first,
                    purpose: "Über das Dashboard angelegt".into(),
                    review_days: None,
                }),
                Err(_) => self.status = "Projekt-Nr. muss eine Zahl sein.".into(),
            },
            Form::None => {}
        }
        self.render();
    }

    fn detail_action(&mut self, id: &str) {
        let mut parts = id.split(':');
        let verb = parts.next().unwrap_or_default();
        let arg = parts.next().and_then(|v| v.parse::<i64>().ok()).unwrap_or_default();
        let extra = parts.next().unwrap_or_default().to_string();
        let request = match verb {
            "approve-project" => Request::ApproveProject { project_id: arg },
            "scan-scope" => Request::Scan { scope_id: Some(arg) },
            "measure-scope" => Request::MeasureScope { scope_id: arg },
            "revoke-scope" => Request::RevokeScope { scope_id: arg },
            "protect" => Request::Protect { resource_id: arg },
            "expendable" => Request::MarkExpendable { resource_id: arg },
            "extend" => Request::Extend { resource_id: arg, days: 7 },
            "promote" => Request::Promote { resource_id: arg },
            "measure" => Request::MeasureResource { resource_id: arg },
            "plan" => Request::CleanupPlan { resource_ids: vec![arg] },
            "approve-plan" => Request::CleanupApprove { plan_id: arg, confirmation: extra },
            "apply-plan" => Request::CleanupApply { plan_id: arg },
            "cancel-plan" => Request::CleanupCancel { plan_id: arg },
            "reconcile-plan" => Request::CleanupReconcile { plan_id: arg },
            "new-scratch" => return self.new_scratch(Some(arg)),
            "open-resource" => return self.open_resource(arg),
            _ => return,
        };
        self.submit(request);
    }
}

fn defer_hide() {
    later(Desktop::hide);
}

fn wire(ui: &Dashboard) {
    let actions = ui.global::<Actions>();
    actions.on_refresh(|| with(|d| d.owner.refresh()));
    actions.on_scan_all(|| with(|d| d.submit(Request::Scan { scope_id: None })));
    actions.on_search(|_| with(|d| d.render()));
    actions.on_open_project(|id| later(move |d| d.open_project(i64::from(id))));
    actions.on_open_resource(|id| later(move |d| d.open_resource(i64::from(id))));
    actions.on_open_ai(|index| {
        later(move |d| {
            if let Some(entry) = d.snapshot.ai.get(index as usize).cloned() {
                d.dialog(dialogs::ai(&entry));
            }
        })
    });
    actions.on_open_hint(|id| {
        later(move |d| {
            if let Some(hint) = d.snapshot.hints.iter().find(|h| h.resource_id == i64::from(id)).cloned() {
                d.dialog(dialogs::hint(&hint));
            }
        })
    });
    actions.on_open_scope(|id| {
        later(move |d| {
            if let Some(scope) = d.snapshot.scopes.iter().find(|s| s.id == i64::from(id)).cloned() {
                d.dialog(dialogs::scope(&scope));
            }
        })
    });
    actions.on_open_plan(|id| {
        later(move |d| {
            if let Some(plan) = d.snapshot.plans.iter().find(|p| p.id == i64::from(id)).cloned() {
                d.dialog(dialogs::plan(&plan));
            }
        })
    });
    actions.on_open_adapter(|id| {
        let id = id.to_string();
        later(move |d| d.dialog(dialogs::adapter(&id)))
    });
    actions.on_new_project(|| later(Desktop::new_project));
    actions.on_new_scratch(|| later(|d| d.new_scratch(None)));
    actions.on_show_cli(|| later(|d| d.dialog(dialogs::message("Generische CLI", dialogs::CLI_HELP))));
    actions.on_detail_action(|id| {
        let id = id.to_string();
        later(move |d| d.detail_action(&id))
    });
    actions.on_submit_form(|a, b| {
        let (a, b) = (a.to_string(), b.to_string());
        later(move |d| d.submit_form(a, b))
    });
    actions.on_set_monitoring(|on| with(|d| d.change_settings(|s| s.monitoring_enabled = on)));
    actions.on_set_notifications(|on| with(|d| d.change_settings(|s| s.notifications_enabled = on)));
    actions.on_set_updates(|on| with(|d| d.change_settings(|s| s.network_updates_enabled = on)));
    actions.on_set_source(|host: SharedString, on| {
        let host = host.to_string();
        with(move |d| {
            d.change_settings(|s| {
                s.update_sources.retain(|h| *h != host);
                if on {
                    s.update_sources.push(host);
                }
            })
        })
    });
    actions.on_save_scratch_root(|path| {
        let path = path.trim().to_string();
        with(move |d| d.change_settings(|s| s.scratch_root = (!path.is_empty()).then_some(path)))
    });
    actions.on_approve_system(|kind| {
        let kind = match kind.as_str() {
            "scoop" => mogumogu::domain::ScopeKind::Scoop,
            "chocolatey" => mogumogu::domain::ScopeKind::Chocolatey,
            _ => mogumogu::domain::ScopeKind::Winget,
        };
        with(move |d| d.submit(Request::ApproveSystem { kind, path: None }))
    });
    actions.on_check_updates(|| with(|d| d.submit(Request::Updates)));
    actions.on_hide_dashboard(defer_hide);
    ui.window().on_close_requested(|| {
        // Defer dropping the component until its close callback returned.
        defer_hide();
        slint::CloseRequestResponse::KeepWindowShown
    });
}
